---
inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  TargetRailsVersion: 7.2
  TargetRubyVersion: 3.2
  Exclude:
    - 'spec/internal/config/**/*'
    - 'spec/internal/db/**/*'
    - 'spec/internal/db/schema.rb'
    - 'vendor/**/*'

Rails:
  Enabled: true

Rails/ApplicationJob:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Layout/LineLength:
  AutoCorrect: true
  Max: 80

Metrics/BlockLength:
  AllowedMethods:
    - "included"
  Exclude:
    - "*.gemspec"
    - "**/*.rake"
    - "**/*.builder"
    - "spec/internal/config/environments/*"
    - "config/routes.rb"
    - "db/migrate/*"
    - "**/*_spec.rb"
    - "spec/factories.rb"
    - "spec/rails_helper.rb"

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*"
