require: rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.4
  Exclude:
    - 'spec/internal/config/**/*'
    - 'spec/internal/db/**/*'
    - 'spec/internal/db/schema.rb'

Rails:
  Enabled: true

StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Layout/LineLength:
  AutoCorrect: true
  Max: 80

Metrics/BlockLength:
  ExcludedMethods:
    - "included"
  Exclude:
    - "*.gemspec"
    - "**/*.rake"
    - "**/*.builder"
    - "spec/internal/config/environments/*"
    - "config/routes.rb"
    - "db/migrate/*"
    - "**/*_spec.rb"
    - "spec/factories.rb"
    - "spec/rails_helper.rb"

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*"
