addons:
  code_climate:
    repo_token: 05e44f79bfab91587e3081a5b09b11f8a81c5e133fa326c4877cc95b26a59b32
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - 2.2.2
env:
  - RAILS_ENV=test
script:
  - bundle exec rspec spec
before_script:
  - bundle exec rake app:db:create
  - bundle exec rake app:db:schema:load
