language: ruby
sudo: false
cache: bundler
dist: bionic
rvm:
  - 2.4.5
  - 2.6.3
env:
  - RAILS_ENV=test
script:
  - bundle exec rspec spec
before_script:
  - bundle exec rake app:db:create
  - bundle exec rake app:db:schema:load
after_script:
  - CODECLIMATE_REPO_TOKEN=05e44f79bfab91587e3081a5b09b11f8a81c5e133fa326c4877cc95b26a59b32 bundle exec codeclimate-test-reporter
